# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        sudo apt-add-repository ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git
    
    - run: git config --global user.name "Perrins99"
    - run: git clone https://github.com/Perrins99/staticwebsite
    - run: cd staticwebsite
    - run: npm ci
    - run: npm run deploy # this command builds and deploys
  

